name: "Pull Request Build"

on:
  - pull_request
jobs:

  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java: [ 11 ]

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: ${{ matrix.java }}
      - name: Build project
        run: ./gradlew test
